import dotenv from 'dotenv';
import mongoose from 'mongoose';
import Question from '../models/Question.js';

dotenv.config();

const questions = [
  // EASY (10)
  {
    title: 'Sum of Two Numbers',
    description: 'Read two integers from input and print their sum.',
    constraints: '1 <= a, b <= 10^9',
    examples: [{ input: '3 5', output: '8', explanation: '3 + 5 = 8' }],
    difficulty: 'Easy',
    tags: ['math', 'basics'],
    starterCode: {
      python: 'a, b = map(int, input().split())\nprint(a + b)',
      javascript: 'const input = require("fs").readFileSync(0, "utf8").trim().split(/\\s+/);\nconst [a, b] = input.map(Number);\nconsole.log(a + b);',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int a = sc.nextInt();\n    int b = sc.nextInt();\n    System.out.println(a + b);\n  }\n}',
      cpp: '#include <iostream>\nusing namespace std;\nint main() {\n  long long a, b;\n  cin >> a >> b;\n  cout << a + b << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '3 5', expectedOutput: '8', isSample: true, isHidden: false },
      { input: '0 0', expectedOutput: '0', isSample: false, isHidden: true },
      { input: '1000000000 1', expectedOutput: '1000000001', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Reverse a String',
    description: 'Read a string and print its reverse.',
    constraints: '1 <= length <= 1000',
    examples: [{ input: 'hello', output: 'olleh', explanation: 'Reverse of hello' }],
    difficulty: 'Easy',
    tags: ['string'],
    starterCode: {
      python: 's = input().strip()\nprint(s[::-1])',
      javascript: 'const s = require("fs").readFileSync(0, "utf8").trim();\nconsole.log(s.split("").reverse().join(""));',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    String s = sc.nextLine();\n    System.out.println(new StringBuilder(s).reverse());\n  }\n}',
      cpp: '#include <iostream>\n#include <algorithm>\nusing namespace std;\nint main() {\n  string s;\n  cin >> s;\n  reverse(s.begin(), s.end());\n  cout << s << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: 'hello', expectedOutput: 'olleh', isSample: true, isHidden: false },
      { input: 'a', expectedOutput: 'a', isSample: false, isHidden: true },
      { input: 'racecar', expectedOutput: 'racecar', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Find Maximum',
    description: 'Read n followed by n integers. Print the maximum value.',
    constraints: '1 <= n <= 1000, -10^9 <= values <= 10^9',
    examples: [{ input: '5\n3 7 2 9 1', output: '9', explanation: 'Maximum is 9' }],
    difficulty: 'Easy',
    tags: ['array'],
    starterCode: {
      python: 'n = int(input())\narr = list(map(int, input().split()))\nprint(max(arr))',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst arr = lines[1].split(" ").map(Number);\nconsole.log(Math.max(...arr));',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    int max = Integer.MIN_VALUE;\n    for (int i = 0; i < n; i++) max = Math.max(max, sc.nextInt());\n    System.out.println(max);\n  }\n}',
      cpp: '#include <iostream>\nusing namespace std;\nint main() {\n  int n, x, mx = -1e18;\n  cin >> n;\n  while (n--) { cin >> x; mx = max(mx, x); }\n  cout << mx << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '5\n3 7 2 9 1', expectedOutput: '9', isSample: true, isHidden: false },
      { input: '1\n-5', expectedOutput: '-5', isSample: false, isHidden: true },
      { input: '3\n100 100 100', expectedOutput: '100', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Count Vowels',
    description: 'Read a lowercase string and print the number of vowels (a, e, i, o, u).',
    constraints: '1 <= length <= 10^5',
    examples: [{ input: 'hello', output: '2', explanation: 'e and o are vowels' }],
    difficulty: 'Easy',
    tags: ['string'],
    starterCode: {
      python: 's = input().strip()\nprint(sum(1 for c in s if c in "aeiou"))',
      javascript: 'const s = require("fs").readFileSync(0, "utf8").trim();\nconsole.log([...s].filter(c => "aeiou".includes(c)).length);',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    String s = new Scanner(System.in).nextLine();\n    int c = 0;\n    for (char ch : s.toCharArray()) if ("aeiou".indexOf(ch) >= 0) c++;\n    System.out.println(c);\n  }\n}',
      cpp: '#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n  string s; cin >> s;\n  int c = 0;\n  for (char ch : s) if (string("aeiou").find(ch) != string::npos) c++;\n  cout << c << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: 'hello', expectedOutput: '2', isSample: true, isHidden: false },
      { input: 'xyz', expectedOutput: '0', isSample: false, isHidden: true },
      { input: 'aeiou', expectedOutput: '5', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Palindrome Check',
    description: 'Read a string and print "YES" if it is a palindrome, else "NO".',
    constraints: '1 <= length <= 1000',
    examples: [{ input: 'level', output: 'YES', explanation: 'Reads same forwards and backwards' }],
    difficulty: 'Easy',
    tags: ['string'],
    starterCode: {
      python: 's = input().strip()\nprint("YES" if s == s[::-1] else "NO")',
      javascript: 'const s = require("fs").readFileSync(0, "utf8").trim();\nconsole.log(s === s.split("").reverse().join("") ? "YES" : "NO");',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    String s = new Scanner(System.in).nextLine();\n    System.out.println(s.equals(new StringBuilder(s).reverse().toString()) ? "YES" : "NO");\n  }\n}',
      cpp: '#include <iostream>\n#include <algorithm>\n#include <string>\nusing namespace std;\nint main() {\n  string s; cin >> s;\n  string t = s; reverse(t.begin(), t.end());\n  cout << (s == t ? "YES" : "NO") << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: 'level', expectedOutput: 'YES', isSample: true, isHidden: false },
      { input: 'hello', expectedOutput: 'NO', isSample: false, isHidden: true },
      { input: 'a', expectedOutput: 'YES', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Factorial',
    description: 'Read a non-negative integer n and print n!.',
    constraints: '0 <= n <= 12',
    examples: [{ input: '5', output: '120', explanation: '5! = 120' }],
    difficulty: 'Easy',
    tags: ['math'],
    starterCode: {
      python: 'n = int(input())\nf = 1\nfor i in range(2, n + 1): f *= i\nprint(f)',
      javascript: 'const n = parseInt(require("fs").readFileSync(0, "utf8").trim(), 10);\nlet f = 1;\nfor (let i = 2; i <= n; i++) f *= i;\nconsole.log(f);',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    int n = new Scanner(System.in).nextInt();\n    long f = 1;\n    for (int i = 2; i <= n; i++) f *= i;\n    System.out.println(f);\n  }\n}',
      cpp: '#include <iostream>\nusing namespace std;\nint main() {\n  int n; cin >> n;\n  long long f = 1;\n  for (int i = 2; i <= n; i++) f *= i;\n  cout << f << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '5', expectedOutput: '120', isSample: true, isHidden: false },
      { input: '0', expectedOutput: '1', isSample: false, isHidden: true },
      { input: '10', expectedOutput: '3628800', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'FizzBuzz Value',
    description: 'Read n. Print FizzBuzz result: Fizz if divisible by 3, Buzz if by 5, FizzBuzz if both, else n.',
    constraints: '1 <= n <= 1000',
    examples: [{ input: '15', output: 'FizzBuzz', explanation: 'Divisible by 3 and 5' }],
    difficulty: 'Easy',
    tags: ['math'],
    starterCode: {
      python: 'n = int(input())\nif n % 15 == 0: print("FizzBuzz")\nelif n % 3 == 0: print("Fizz")\nelif n % 5 == 0: print("Buzz")\nelse: print(n)',
      javascript: 'const n = parseInt(require("fs").readFileSync(0, "utf8").trim(), 10);\nif (n % 15 === 0) console.log("FizzBuzz");\nelse if (n % 3 === 0) console.log("Fizz");\nelse if (n % 5 === 0) console.log("Buzz");\nelse console.log(n);',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    int n = new Scanner(System.in).nextInt();\n    if (n % 15 == 0) System.out.println("FizzBuzz");\n    else if (n % 3 == 0) System.out.println("Fizz");\n    else if (n % 5 == 0) System.out.println("Buzz");\n    else System.out.println(n);\n  }\n}',
      cpp: '#include <iostream>\nusing namespace std;\nint main() {\n  int n; cin >> n;\n  if (n % 15 == 0) cout << "FizzBuzz";\n  else if (n % 3 == 0) cout << "Fizz";\n  else if (n % 5 == 0) cout << "Buzz";\n  else cout << n;\n  cout << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '15', expectedOutput: 'FizzBuzz', isSample: true, isHidden: false },
      { input: '9', expectedOutput: 'Fizz', isSample: false, isHidden: true },
      { input: '7', expectedOutput: '7', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Sum of Digits',
    description: 'Read a non-negative integer and print the sum of its digits.',
    constraints: '0 <= n <= 10^12',
    examples: [{ input: '12345', output: '15', explanation: '1+2+3+4+5=15' }],
    difficulty: 'Easy',
    tags: ['math'],
    starterCode: {
      python: 'n = input().strip()\nprint(sum(int(d) for d in n))',
      javascript: 'const n = require("fs").readFileSync(0, "utf8").trim();\nconsole.log([...n].reduce((s, d) => s + +d, 0));',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    String n = new Scanner(System.in).next();\n    int s = 0;\n    for (char c : n.toCharArray()) s += c - \'0\';\n    System.out.println(s);\n  }\n}',
      cpp: '#include <iostream>\n#include <string>\nusing namespace std;\nint main() {\n  string n; cin >> n;\n  int s = 0;\n  for (char c : n) s += c - \'0\';\n  cout << s << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '12345', expectedOutput: '15', isSample: true, isHidden: false },
      { input: '0', expectedOutput: '0', isSample: false, isHidden: true },
      { input: '999', expectedOutput: '27', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Even or Odd',
    description: 'Read an integer and print EVEN or ODD.',
    constraints: '-10^9 <= n <= 10^9',
    examples: [{ input: '4', output: 'EVEN', explanation: '4 is even' }],
    difficulty: 'Easy',
    tags: ['math'],
    starterCode: {
      python: 'n = int(input())\nprint("EVEN" if n % 2 == 0 else "ODD")',
      javascript: 'const n = parseInt(require("fs").readFileSync(0, "utf8").trim(), 10);\nconsole.log(n % 2 === 0 ? "EVEN" : "ODD");',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    long n = new Scanner(System.in).nextLong();\n    System.out.println(n % 2 == 0 ? "EVEN" : "ODD");\n  }\n}',
      cpp: '#include <iostream>\nusing namespace std;\nint main() {\n  long long n; cin >> n;\n  cout << (n % 2 == 0 ? "EVEN" : "ODD") << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '4', expectedOutput: 'EVEN', isSample: true, isHidden: false },
      { input: '7', expectedOutput: 'ODD', isSample: false, isHidden: true },
      { input: '0', expectedOutput: 'EVEN', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Array Sum',
    description: 'Read n followed by n integers. Print the sum of all elements.',
    constraints: '1 <= n <= 10^5',
    examples: [{ input: '4\n1 2 3 4', output: '10', explanation: 'Sum is 10' }],
    difficulty: 'Easy',
    tags: ['array'],
    starterCode: {
      python: 'n = int(input())\narr = list(map(int, input().split()))\nprint(sum(arr))',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst arr = lines[1].split(" ").map(Number);\nconsole.log(arr.reduce((a, b) => a + b, 0));',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt(), s = 0;\n    for (int i = 0; i < n; i++) s += sc.nextInt();\n    System.out.println(s);\n  }\n}',
      cpp: '#include <iostream>\nusing namespace std;\nint main() {\n  int n, x, s = 0;\n  cin >> n;\n  while (n--) { cin >> x; s += x; }\n  cout << s << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '4\n1 2 3 4', expectedOutput: '10', isSample: true, isHidden: false },
      { input: '1\n100', expectedOutput: '100', isSample: false, isHidden: true },
      { input: '3\n-1 0 1', expectedOutput: '0', isSample: false, isHidden: true },
    ],
  },
  // MEDIUM (10)
  {
    title: 'Two Sum Indices',
    description: 'Read n, array of n integers, then target. Print 0-based indices i j (i < j) such that arr[i]+arr[j]=target.',
    constraints: '2 <= n <= 10^4, exactly one solution exists',
    examples: [{ input: '4\n2 7 11 15\n9', output: '0 1', explanation: '2+7=9' }],
    difficulty: 'Medium',
    tags: ['array', 'hash-map'],
    starterCode: {
      python: 'n = int(input())\narr = list(map(int, input().split()))\ntarget = int(input())\nseen = {}\nfor i, v in enumerate(arr):\n  if target - v in seen:\n    print(seen[target - v], i)\n    break\n  seen[v] = i',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst arr = lines[1].split(" ").map(Number);\nconst target = +lines[2];\nconst map = new Map();\nfor (let i = 0; i < arr.length; i++) {\n  if (map.has(target - arr[i])) { console.log(map.get(target - arr[i]), i); break; }\n  map.set(arr[i], i);\n}',
      java: 'import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    int[] arr = new int[n];\n    for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n    int target = sc.nextInt();\n    Map<Integer, Integer> map = new HashMap<>();\n    for (int i = 0; i < n; i++) {\n      if (map.containsKey(target - arr[i])) { System.out.println(map.get(target - arr[i]) + " " + i); break; }\n      map.put(arr[i], i);\n    }\n  }\n}',
      cpp: '#include <iostream>\n#include <unordered_map>\nusing namespace std;\nint main() {\n  int n; cin >> n;\n  vector<int> arr(n);\n  for (int i = 0; i < n; i++) cin >> arr[i];\n  int target; cin >> target;\n  unordered_map<int,int> mp;\n  for (int i = 0; i < n; i++) {\n    if (mp.count(target - arr[i])) { cout << mp[target - arr[i]] << " " << i << endl; break; }\n    mp[arr[i]] = i;\n  }\n  return 0;\n}',
    },
    testCases: [
      { input: '4\n2 7 11 15\n9', expectedOutput: '0 1', isSample: true, isHidden: false },
      { input: '2\n3 3\n6', expectedOutput: '0 1', isSample: false, isHidden: true },
      { input: '5\n1 2 3 4 5\n9', expectedOutput: '3 4', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Valid Parentheses',
    description: 'Read a string of brackets ()[]{} and print VALID or INVALID.',
    constraints: '1 <= length <= 10^4',
    examples: [{ input: '()[]{}', output: 'VALID', explanation: 'All brackets matched' }],
    difficulty: 'Medium',
    tags: ['stack', 'string'],
    starterCode: {
      python: 's = input().strip()\nstack = []\npairs = {\')\': \'(\', \']\': \'[\', \'}\': \'{\'}\nfor c in s:\n  if c in \'([{\': stack.append(c)\n  elif not stack or stack.pop() != pairs[c]: print("INVALID"); break\nelse: print("VALID" if not stack else "INVALID")',
      javascript: 'const s = require("fs").readFileSync(0, "utf8").trim();\nconst st = [], pairs = {\')\':\'(\', \']\':\'[\', \'}\':\'{\'};\nfor (const c of s) {\n  if ("([{".includes(c)) st.push(c);\n  else if (!st.length || st.pop() !== pairs[c]) { console.log("INVALID"); process.exit(0); }\n}\nconsole.log(st.length ? "INVALID" : "VALID");',
      java: 'import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    String s = new Scanner(System.in).nextLine();\n    Deque<Character> st = new ArrayDeque<>();\n    Map<Character, Character> p = Map.of(\')\', \'(\', \']\', \'[\', \'}\', \'{\');\n    for (char c : s.toCharArray()) {\n      if ("([{".indexOf(c) >= 0) st.push(c);\n      else if (st.isEmpty() || st.pop() != p.get(c)) { System.out.println("INVALID"); return; }\n    }\n    System.out.println(st.isEmpty() ? "VALID" : "INVALID");\n  }\n}',
      cpp: '#include <iostream>\n#include <stack>\n#include <string>\nusing namespace std;\nint main() {\n  string s; cin >> s;\n  stack<char> st;\n  for (char c : s) {\n    if (c==\'(\'||c==\'[\'||c==\'{\') st.push(c);\n    else {\n      if (st.empty()) { cout << "INVALID" << endl; return 0; }\n      char t = st.top(); st.pop();\n      if ((c==\')\'&&t!=\'(\')||(c==\']\'&&t!=\'[\')||(c==\'}\'&&t!=\'{\')) { cout << "INVALID" << endl; return 0; }\n    }\n  }\n  cout << (st.empty() ? "VALID" : "INVALID") << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '()[]{}', expectedOutput: 'VALID', isSample: true, isHidden: false },
      { input: '(]', expectedOutput: 'INVALID', isSample: false, isHidden: true },
      { input: '{[]}', expectedOutput: 'VALID', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Binary Search',
    description: 'Read sorted array (n, then n values), then target. Print index or -1.',
    constraints: '1 <= n <= 10^5',
    examples: [{ input: '5\n1 3 5 7 9\n5', output: '2', explanation: '5 is at index 2' }],
    difficulty: 'Medium',
    tags: ['binary-search'],
    starterCode: {
      python: 'n = int(input())\narr = list(map(int, input().split()))\ntarget = int(input())\nl, r = 0, n - 1\nwhile l <= r:\n  m = (l + r) // 2\n  if arr[m] == target: print(m); break\n  elif arr[m] < target: l = m + 1\n  else: r = m - 1\nelse: print(-1)',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst arr = lines[1].split(" ").map(Number);\nconst target = +lines[2];\nlet l = 0, r = arr.length - 1;\nwhile (l <= r) {\n  const m = (l + r) >> 1;\n  if (arr[m] === target) { console.log(m); process.exit(0); }\n  if (arr[m] < target) l = m + 1; else r = m - 1;\n}\nconsole.log(-1);',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    int[] arr = new int[n];\n    for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n    int target = sc.nextInt(), l = 0, r = n - 1;\n    while (l <= r) {\n      int m = (l + r) / 2;\n      if (arr[m] == target) { System.out.println(m); return; }\n      if (arr[m] < target) l = m + 1; else r = m - 1;\n    }\n    System.out.println(-1);\n  }\n}',
      cpp: '#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n  int n; cin >> n;\n  vector<int> arr(n);\n  for (int i = 0; i < n; i++) cin >> arr[i];\n  int target; cin >> target;\n  int l = 0, r = n - 1;\n  while (l <= r) {\n    int m = (l + r) / 2;\n    if (arr[m] == target) { cout << m << endl; return 0; }\n    if (arr[m] < target) l = m + 1; else r = m - 1;\n  }\n  cout << -1 << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '5\n1 3 5 7 9\n5', expectedOutput: '2', isSample: true, isHidden: false },
      { input: '3\n1 2 3\n4', expectedOutput: '-1', isSample: false, isHidden: true },
      { input: '1\n10\n10', expectedOutput: '0', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Merge Sorted Arrays',
    description: 'Read n, array A, m, array B. Print merged sorted array.',
    constraints: '0 <= n,m <= 10^4',
    examples: [{ input: '3\n1 3 5\n3\n2 4 6', output: '1 2 3 4 5 6', explanation: 'Merged sorted' }],
    difficulty: 'Medium',
    tags: ['array', 'two-pointers'],
    starterCode: {
      python: 'n = int(input())\na = list(map(int, input().split())) if n else []\nm = int(input())\nb = list(map(int, input().split())) if m else []\ni = j = 0\nres = []\nwhile i < len(a) and j < len(b):\n  if a[i] <= b[j]: res.append(a[i]); i += 1\n  else: res.append(b[j]); j += 1\nres.extend(a[i:]); res.extend(b[j:])\nprint(*res)',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nlet idx = 0;\nconst n = +lines[idx++];\nconst a = n ? lines[idx++].split(" ").map(Number) : [];\nconst m = +lines[idx++];\nconst b = m ? lines[idx++].split(" ").map(Number) : [];\nlet i = 0, j = 0, res = [];\nwhile (i < a.length && j < b.length) res.push(a[i] <= b[j] ? a[i++] : b[j++]);\nwhile (i < a.length) res.push(a[i++]);\nwhile (j < b.length) res.push(b[j++]);\nconsole.log(res.join(" "));',
      java: 'import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    int[] a = new int[n];\n    for (int i = 0; i < n; i++) a[i] = sc.nextInt();\n    int m = sc.nextInt();\n    int[] b = new int[m];\n    for (int i = 0; i < m; i++) b[i] = sc.nextInt();\n    int i = 0, j = 0;\n    StringBuilder sb = new StringBuilder();\n    while (i < n && j < m) sb.append((a[i] <= b[j] ? a[i++] : b[j++])).append(" ");\n    while (i < n) sb.append(a[i++]).append(" ");\n    while (j < m) sb.append(b[j++]).append(" ");\n    System.out.println(sb.toString().trim());\n  }\n}',
      cpp: '#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n  int n; cin >> n;\n  vector<int> a(n);\n  for (int i = 0; i < n; i++) cin >> a[i];\n  int m; cin >> m;\n  vector<int> b(m);\n  for (int i = 0; i < m; i++) cin >> b[i];\n  int i = 0, j = 0;\n  vector<int> res;\n  while (i < n && j < m) res.push_back(a[i] <= b[j] ? a[i++] : b[j++]);\n  while (i < n) res.push_back(a[i++]);\n  while (j < m) res.push_back(b[j++]);\n  for (int k = 0; k < (int)res.size(); k++) { if (k) cout << " "; cout << res[k]; }\n  cout << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '3\n1 3 5\n3\n2 4 6', expectedOutput: '1 2 3 4 5 6', isSample: true, isHidden: false },
      { input: '0\n\n2\n1 2', expectedOutput: '1 2', isSample: false, isHidden: true },
      { input: '2\n5 10\n0\n', expectedOutput: '5 10', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Longest Word',
    description: 'Read a sentence and print the longest word (if tie, first occurrence).',
    constraints: '1 <= length <= 10^5',
    examples: [{ input: 'the quick brown fox', output: 'quick', explanation: 'quick has 5 letters' }],
    difficulty: 'Medium',
    tags: ['string'],
    starterCode: {
      python: 's = input().strip().split()\nprint(max(s, key=len))',
      javascript: 'const words = require("fs").readFileSync(0, "utf8").trim().split(/\\s+/);\nconsole.log(words.reduce((a, b) => b.length > a.length ? b : a));',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    String[] words = new Scanner(System.in).nextLine().split("\\\\s+");\n    String best = words[0];\n    for (String w : words) if (w.length() > best.length()) best = w;\n    System.out.println(best);\n  }\n}',
      cpp: '#include <iostream>\n#include <sstream>\n#include <string>\nusing namespace std;\nint main() {\n  string line; getline(cin, line);\n  stringstream ss(line);\n  string w, best;\n  while (ss >> w) if (best.empty() || w.size() > best.size()) best = w;\n  cout << best << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: 'the quick brown fox', expectedOutput: 'quick', isSample: true, isHidden: false },
      { input: 'a bb ccc bb', expectedOutput: 'ccc', isSample: false, isHidden: true },
      { input: 'hello', expectedOutput: 'hello', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Remove Duplicates Count',
    description: 'Read sorted array (n, values). Print count after removing duplicates in-place style.',
    constraints: '1 <= n <= 10^5',
    examples: [{ input: '5\n1 1 2 2 3', output: '3', explanation: 'Unique: 1,2,3' }],
    difficulty: 'Medium',
    tags: ['array', 'two-pointers'],
    starterCode: {
      python: 'n = int(input())\narr = list(map(int, input().split()))\nif not arr: print(0)\nelse:\n  k = 1\n  for i in range(1, n):\n    if arr[i] != arr[k-1]: arr[k] = arr[i]; k += 1\n  print(k)',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst arr = lines[1].split(" ").map(Number);\nif (!arr.length) console.log(0);\nelse {\n  let k = 1;\n  for (let i = 1; i < arr.length; i++) if (arr[i] !== arr[k-1]) arr[k++] = arr[i];\n  console.log(k);\n}',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    int[] arr = new int[n];\n    for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n    if (n == 0) { System.out.println(0); return; }\n    int k = 1;\n    for (int i = 1; i < n; i++) if (arr[i] != arr[k-1]) arr[k++] = arr[i];\n    System.out.println(k);\n  }\n}',
      cpp: '#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n  int n; cin >> n;\n  vector<int> arr(n);\n  for (int i = 0; i < n; i++) cin >> arr[i];\n  if (n == 0) { cout << 0 << endl; return 0; }\n  int k = 1;\n  for (int i = 1; i < n; i++) if (arr[i] != arr[k-1]) arr[k++] = arr[i];\n  cout << k << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '5\n1 1 2 2 3', expectedOutput: '3', isSample: true, isHidden: false },
      { input: '3\n1 1 1', expectedOutput: '1', isSample: false, isHidden: true },
      { input: '4\n1 2 3 4', expectedOutput: '4', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Rotate Array Right',
    description: 'Read n, array, k. Print array rotated right by k.',
    constraints: '1 <= n <= 10^5, 0 <= k <= 10^5',
    examples: [{ input: '5\n1 2 3 4 5\n2', output: '4 5 1 2 3', explanation: 'Rotate right by 2' }],
    difficulty: 'Medium',
    tags: ['array'],
    starterCode: {
      python: 'n = int(input())\narr = list(map(int, input().split()))\nk = int(input()) % n\nprint(*arr[-k:] + arr[:-k] if k else arr)',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst arr = lines[1].split(" ").map(Number);\nconst k = (+lines[2]) % arr.length;\nconst res = k ? [...arr.slice(-k), ...arr.slice(0, -k)] : arr;\nconsole.log(res.join(" "));',
      java: 'import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    int[] arr = new int[n];\n    for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n    int k = sc.nextInt() % n;\n    int[] res = new int[n];\n    for (int i = 0; i < n; i++) res[(i + k) % n] = arr[i];\n    for (int i = 0; i < n; i++) System.out.print(res[i] + (i + 1 < n ? " " : ""));\n    System.out.println();\n  }\n}',
      cpp: '#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n  int n; cin >> n;\n  vector<int> arr(n);\n  for (int i = 0; i < n; i++) cin >> arr[i];\n  int k; cin >> k;\n  k %= n;\n  vector<int> res(n);\n  for (int i = 0; i < n; i++) res[(i + k) % n] = arr[i];\n  for (int i = 0; i < n; i++) { if (i) cout << " "; cout << res[i]; }\n  cout << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '5\n1 2 3 4 5\n2', expectedOutput: '4 5 1 2 3', isSample: true, isHidden: false },
      { input: '3\n1 2 3\n0', expectedOutput: '1 2 3', isSample: false, isHidden: true },
      { input: '4\n10 20 30 40\n4', expectedOutput: '10 20 30 40', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Count Occurrences',
    description: 'Read n, array, then x. Print count of x in array.',
    constraints: '1 <= n <= 10^5',
    examples: [{ input: '6\n1 2 2 3 2 4\n2', output: '3', explanation: '2 appears 3 times' }],
    difficulty: 'Medium',
    tags: ['array'],
    starterCode: {
      python: 'n = int(input())\narr = list(map(int, input().split()))\nx = int(input())\nprint(arr.count(x))',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst arr = lines[1].split(" ").map(Number);\nconst x = +lines[2];\nconsole.log(arr.filter(v => v === x).length);',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt(), c = 0, x = 0;\n    int[] arr = new int[n];\n    for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n    x = sc.nextInt();\n    for (int v : arr) if (v == x) c++;\n    System.out.println(c);\n  }\n}',
      cpp: '#include <iostream>\nusing namespace std;\nint main() {\n  int n, x, target, c = 0;\n  cin >> n;\n  int arr[100005];\n  for (int i = 0; i < n; i++) cin >> arr[i];\n  cin >> target;\n  for (int i = 0; i < n; i++) if (arr[i] == target) c++;\n  cout << c << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '6\n1 2 2 3 2 4\n2', expectedOutput: '3', isSample: true, isHidden: false },
      { input: '3\n5 5 5\n5', expectedOutput: '3', isSample: false, isHidden: true },
      { input: '4\n1 2 3 4\n9', expectedOutput: '0', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Anagram Check',
    description: 'Read two strings. Print YES if anagrams, else NO.',
    constraints: '1 <= length <= 10^5, lowercase letters',
    examples: [{ input: 'listen\nsilent', output: 'YES', explanation: 'Same letters' }],
    difficulty: 'Medium',
    tags: ['string', 'hash-map'],
    starterCode: {
      python: 'a = input().strip()\nb = input().strip()\nprint("YES" if sorted(a) == sorted(b) else "NO")',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst sort = s => s.split("").sort().join("");\nconsole.log(sort(lines[0]) === sort(lines[1]) ? "YES" : "NO");',
      java: 'import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    char[] a = sc.nextLine().toCharArray();\n    char[] b = sc.nextLine().toCharArray();\n    Arrays.sort(a); Arrays.sort(b);\n    System.out.println(Arrays.equals(a, b) ? "YES" : "NO");\n  }\n}',
      cpp: '#include <iostream>\n#include <algorithm>\n#include <string>\nusing namespace std;\nint main() {\n  string a, b; cin >> a >> b;\n  sort(a.begin(), a.end()); sort(b.begin(), b.end());\n  cout << (a == b ? "YES" : "NO") << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: 'listen\nsilent', expectedOutput: 'YES', isSample: true, isHidden: false },
      { input: 'hello\nworld', expectedOutput: 'NO', isSample: false, isHidden: true },
      { input: 'aa\naa', expectedOutput: 'YES', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Missing Number',
    description: 'Read n then n distinct integers from 0..n. Print the missing number.',
    constraints: '1 <= n <= 10^5',
    examples: [{ input: '3\n3 0 1', output: '2', explanation: '2 is missing from 0..3' }],
    difficulty: 'Medium',
    tags: ['math', 'array'],
    starterCode: {
      python: 'n = int(input())\narr = list(map(int, input().split()))\nprint(n * (n + 1) // 2 - sum(arr))',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst n = +lines[0];\nconst arr = lines[1].split(" ").map(Number);\nconst expected = n * (n + 1) / 2;\nconsole.log(expected - arr.reduce((a, b) => a + b, 0));',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt(), s = 0;\n    for (int i = 0; i < n; i++) s += sc.nextInt();\n    System.out.println(n * (n + 1) / 2 - s);\n  }\n}',
      cpp: '#include <iostream>\nusing namespace std;\nint main() {\n  int n, s = 0, x;\n  cin >> n;\n  for (int i = 0; i < n; i++) { cin >> x; s += x; }\n  cout << n * (n + 1) / 2 - s << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '3\n3 0 1', expectedOutput: '2', isSample: true, isHidden: false },
      { input: '1\n0', expectedOutput: '1', isSample: false, isHidden: true },
      { input: '5\n0 1 2 4 5', expectedOutput: '3', isSample: false, isHidden: true },
    ],
  },
  // HARD (10) - continuing with simplified stdin/stdout versions
  {
    title: 'Longest Substring Without Repeating',
    description: 'Read a string. Print length of longest substring without repeating characters.',
    constraints: '1 <= length <= 10^5',
    examples: [{ input: 'abcabcbb', output: '3', explanation: 'abc has length 3' }],
    difficulty: 'Hard',
    tags: ['sliding-window', 'string'],
    starterCode: {
      python: 's = input().strip()\nseen = {}\nstart = best = 0\nfor i, c in enumerate(s):\n  if c in seen and seen[c] >= start: start = seen[c] + 1\n  seen[c] = i\n  best = max(best, i - start + 1)\nprint(best)',
      javascript: 'const s = require("fs").readFileSync(0, "utf8").trim();\nconst seen = new Map();\nlet start = 0, best = 0;\nfor (let i = 0; i < s.length; i++) {\n  if (seen.has(s[i]) && seen.get(s[i]) >= start) start = seen.get(s[i]) + 1;\n  seen.set(s[i], i);\n  best = Math.max(best, i - start + 1);\n}\nconsole.log(best);',
      java: 'import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    String s = new Scanner(System.in).nextLine();\n    Map<Character, Integer> seen = new HashMap<>();\n    int start = 0, best = 0;\n    for (int i = 0; i < s.length(); i++) {\n      char c = s.charAt(i);\n      if (seen.containsKey(c) && seen.get(c) >= start) start = seen.get(c) + 1;\n      seen.put(c, i);\n      best = Math.max(best, i - start + 1);\n    }\n    System.out.println(best);\n  }\n}',
      cpp: '#include <iostream>\n#include <string>\n#include <unordered_map>\nusing namespace std;\nint main() {\n  string s; cin >> s;\n  unordered_map<char,int> seen;\n  int start = 0, best = 0;\n  for (int i = 0; i < (int)s.size(); i++) {\n    if (seen.count(s[i]) && seen[s[i]] >= start) start = seen[s[i]] + 1;\n    seen[s[i]] = i;\n    best = max(best, i - start + 1);\n  }\n  cout << best << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: 'abcabcbb', expectedOutput: '3', isSample: true, isHidden: false },
      { input: 'bbbbb', expectedOutput: '1', isSample: false, isHidden: true },
      { input: 'pwwkew', expectedOutput: '3', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Spiral Matrix Order',
    description: 'Read r, c, then r*c matrix elements row-wise. Print spiral order space-separated.',
    constraints: '1 <= r,c <= 100',
    examples: [{ input: '3 3\n1 2 3\n4 5 6\n7 8 9', output: '1 2 3 6 9 8 7 4 5', explanation: 'Spiral traversal' }],
    difficulty: 'Hard',
    tags: ['matrix'],
    starterCode: {
      python: 'r, c = map(int, input().split())\nmat = [list(map(int, input().split())) for _ in range(r)]\nt, b, l, ri = 0, r-1, 0, c-1\nres = []\nwhile t <= b and l <= ri:\n  for j in range(l, ri+1): res.append(mat[t][j])\n  t += 1\n  for i in range(t, b+1): res.append(mat[i][ri])\n  ri -= 1\n  if t <= b:\n    for j in range(ri, l-1, -1): res.append(mat[b][j])\n    b -= 1\n  if l <= ri:\n    for i in range(b, t-1, -1): res.append(mat[i][l])\n    l += 1\nprint(*res)',
      javascript: 'const fs = require("fs");\nconst lines = fs.readFileSync(0, "utf8").trim().split("\\n");\nconst [r, c] = lines[0].split(" ").map(Number);\nconst mat = lines.slice(1, 1 + r).map(l => l.split(" ").map(Number));\nlet t = 0, b = r - 1, l = 0, ri = c - 1, res = [];\nwhile (t <= b && l <= ri) {\n  for (let j = l; j <= ri; j++) res.push(mat[t][j]);\n  t++;\n  for (let i = t; i <= b; i++) res.push(mat[i][ri]);\n  ri--;\n  if (t <= b) for (let j = ri; j >= l; j--) res.push(mat[b][j]);\n  b--;\n  if (l <= ri) for (let i = b; i >= t; i--) res.push(mat[i][l]);\n  l++;\n}\nconsole.log(res.join(" "));',
      java: 'import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int r = sc.nextInt(), c = sc.nextInt();\n    int[][] mat = new int[r][c];\n    for (int i = 0; i < r; i++) for (int j = 0; j < c; j++) mat[i][j] = sc.nextInt();\n    int t = 0, b = r - 1, l = 0, ri = c - 1;\n    List<Integer> res = new ArrayList<>();\n    while (t <= b && l <= ri) {\n      for (int j = l; j <= ri; j++) res.add(mat[t][j]);\n      t++;\n      for (int i = t; i <= b; i++) res.add(mat[i][ri]);\n      ri--;\n      if (t <= b) for (int j = ri; j >= l; j--) res.add(mat[b][j]);\n      b--;\n      if (l <= ri) for (int i = b; i >= t; i--) res.add(mat[i][l]);\n      l++;\n    }\n    System.out.println(res.stream().map(String::valueOf).reduce((a,b)->a+" "+b).orElse(""));\n  }\n}',
      cpp: '#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n  int r, c; cin >> r >> c;\n  vector<vector<int>> mat(r, vector<int>(c));\n  for (int i = 0; i < r; i++) for (int j = 0; j < c; j++) cin >> mat[i][j];\n  int t = 0, b = r - 1, l = 0, ri = c - 1;\n  vector<int> res;\n  while (t <= b && l <= ri) {\n    for (int j = l; j <= ri; j++) res.push_back(mat[t][j]);\n    t++;\n    for (int i = t; i <= b; i++) res.push_back(mat[i][ri]);\n    ri--;\n    if (t <= b) for (int j = ri; j >= l; j--) res.push_back(mat[b][j]);\n    b--;\n    if (l <= ri) for (int i = b; i >= t; i--) res.push_back(mat[i][l]);\n    l++;\n  }\n  for (int i = 0; i < (int)res.size(); i++) { if (i) cout << " "; cout << res[i]; }\n  cout << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '3 3\n1 2 3\n4 5 6\n7 8 9', expectedOutput: '1 2 3 6 9 8 7 4 5', isSample: true, isHidden: false },
      { input: '1 3\n1 2 3', expectedOutput: '1 2 3', isSample: false, isHidden: true },
      { input: '2 2\n1 2\n3 4', expectedOutput: '1 2 4 3', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Kth Largest Element',
    description: 'Read n, array, k. Print the kth largest element (1-indexed).',
    constraints: '1 <= k <= n <= 10^4',
    examples: [{ input: '6\n3 2 1 5 6 4\n2', output: '5', explanation: '2nd largest is 5' }],
    difficulty: 'Hard',
    tags: ['heap', 'sorting'],
    starterCode: {
      python: 'n = int(input())\narr = list(map(int, input().split()))\nk = int(input())\narr.sort(reverse=True)\nprint(arr[k-1])',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst arr = lines[1].split(" ").map(Number).sort((a,b)=>b-a);\nconsole.log(arr[+lines[2] - 1]);',
      java: 'import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    Integer[] arr = new Integer[n];\n    for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n    int k = sc.nextInt();\n    Arrays.sort(arr, Collections.reverseOrder());\n    System.out.println(arr[k-1]);\n  }\n}',
      cpp: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\nint main() {\n  int n; cin >> n;\n  vector<int> arr(n);\n  for (int i = 0; i < n; i++) cin >> arr[i];\n  int k; cin >> k;\n  sort(arr.begin(), arr.end(), greater<int>());\n  cout << arr[k-1] << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '6\n3 2 1 5 6 4\n2', expectedOutput: '5', isSample: true, isHidden: false },
      { input: '3\n2 2 3\n1', expectedOutput: '3', isSample: false, isHidden: true },
      { input: '5\n10 9 8 7 6\n5', expectedOutput: '6', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Coin Change Minimum',
    description: 'Read amount n, then coin count m and m coin values. Print minimum coins to make amount or -1.',
    constraints: '0 <= amount <= 10^4, 1 <= m <= 100',
    examples: [{ input: '11\n3\n1 2 5', output: '3', explanation: '5+5+1=11' }],
    difficulty: 'Hard',
    tags: ['dp'],
    starterCode: {
      python: 'amount = int(input())\nm = int(input())\ncoins = list(map(int, input().split()))\ndp = [float("inf")] * (amount + 1)\ndp[0] = 0\nfor a in range(1, amount + 1):\n  for c in coins:\n    if c <= a: dp[a] = min(dp[a], dp[a-c] + 1)\nprint(-1 if dp[amount] == float("inf") else dp[amount])',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst amount = +lines[0];\nconst coins = lines[2].split(" ").map(Number);\nconst dp = Array(amount + 1).fill(Infinity);\ndp[0] = 0;\nfor (let a = 1; a <= amount; a++) for (const c of coins) if (c <= a) dp[a] = Math.min(dp[a], dp[a-c] + 1);\nconsole.log(dp[amount] === Infinity ? -1 : dp[amount]);',
      java: 'import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int amount = sc.nextInt(), m = sc.nextInt();\n    int[] coins = new int[m];\n    for (int i = 0; i < m; i++) coins[i] = sc.nextInt();\n    int[] dp = new int[amount + 1];\n    Arrays.fill(dp, amount + 1);\n    dp[0] = 0;\n    for (int a = 1; a <= amount; a++) for (int c : coins) if (c <= a) dp[a] = Math.min(dp[a], dp[a-c] + 1);\n    System.out.println(dp[amount] > amount ? -1 : dp[amount]);\n  }\n}',
      cpp: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\nint main() {\n  int amount, m; cin >> amount >> m;\n  vector<int> coins(m);\n  for (int i = 0; i < m; i++) cin >> coins[i];\n  vector<int> dp(amount + 1, amount + 1);\n  dp[0] = 0;\n  for (int a = 1; a <= amount; a++) for (int c : coins) if (c <= a) dp[a] = min(dp[a], dp[a-c] + 1);\n  cout << (dp[amount] > amount ? -1 : dp[amount]) << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '11\n3\n1 2 5', expectedOutput: '3', isSample: true, isHidden: false },
      { input: '3\n1\n2', expectedOutput: '-1', isSample: false, isHidden: true },
      { input: '0\n1\n1', expectedOutput: '0', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Longest Increasing Subsequence Length',
    description: 'Read n and array. Print length of LIS.',
    constraints: '1 <= n <= 2500',
    examples: [{ input: '6\n10 9 2 5 3 7', output: '3', explanation: 'LIS: 2,5,7 or 2,3,7' }],
    difficulty: 'Hard',
    tags: ['dp', 'binary-search'],
    starterCode: {
      python: 'n = int(input())\narr = list(map(int, input().split()))\npiles = []\nfor x in arr:\n  lo, hi = 0, len(piles)\n  while lo < hi:\n    mid = (lo + hi) // 2\n    if piles[mid] < x: lo = mid + 1\n    else: hi = mid\n  if lo == len(piles): piles.append(x)\n  else: piles[lo] = x\nprint(len(piles))',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst arr = lines[1].split(" ").map(Number);\nconst piles = [];\nfor (const x of arr) {\n  let lo = 0, hi = piles.length;\n  while (lo < hi) { const mid = (lo + hi) >> 1; if (piles[mid] < x) lo = mid + 1; else hi = mid; }\n  if (lo === piles.length) piles.push(x); else piles[lo] = x;\n}\nconsole.log(piles.length);',
      java: 'import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    int[] arr = new int[n];\n    for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n    List<Integer> piles = new ArrayList<>();\n    for (int x : arr) {\n      int lo = 0, hi = piles.size();\n      while (lo < hi) { int mid = (lo + hi) / 2; if (piles.get(mid) < x) lo = mid + 1; else hi = mid; }\n      if (lo == piles.size()) piles.add(x); else piles.set(lo, x);\n    }\n    System.out.println(piles.size());\n  }\n}',
      cpp: '#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n  int n; cin >> n;\n  vector<int> arr(n), piles;\n  for (int i = 0; i < n; i++) cin >> arr[i];\n  for (int x : arr) {\n    auto it = lower_bound(piles.begin(), piles.end(), x);\n    if (it == piles.end()) piles.push_back(x); else *it = x;\n  }\n  cout << piles.size() << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '6\n10 9 2 5 3 7', expectedOutput: '3', isSample: true, isHidden: false },
      { input: '3\n1 2 3', expectedOutput: '3', isSample: false, isHidden: true },
      { input: '4\n4 3 2 1', expectedOutput: '1', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Word Break Possible',
    description: 'Read string s, then n and n dictionary words. Print YES if s can be segmented using dictionary words.',
    constraints: '1 <= len(s) <= 300',
    examples: [{ input: 'leetcode\n2\nleet code', output: 'YES', explanation: 'leet + code' }],
    difficulty: 'Hard',
    tags: ['dp'],
    starterCode: {
      python: 's = input().strip()\nn = int(input())\nwords = set(input().split())\ndp = [False] * (len(s) + 1)\ndp[0] = True\nfor i in range(1, len(s) + 1):\n  for j in range(i):\n    if dp[j] and s[j:i] in words:\n      dp[i] = True\n      break\nprint("YES" if dp[len(s)] else "NO")',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst s = lines[0];\nconst words = new Set(lines[2].split(" "));\nconst dp = Array(s.length + 1).fill(false);\ndp[0] = true;\nfor (let i = 1; i <= s.length; i++) {\n  for (let j = 0; j < i; j++) {\n    if (dp[j] && words.has(s.slice(j, i))) { dp[i] = true; break; }\n  }\n}\nconsole.log(dp[s.length] ? "YES" : "NO");',
      java: 'import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    String s = sc.nextLine();\n    int n = sc.nextInt(); sc.nextLine();\n    Set<String> words = new HashSet<>(Arrays.asList(sc.nextLine().split(" ")));\n    boolean[] dp = new boolean[s.length() + 1];\n    dp[0] = true;\n    for (int i = 1; i <= s.length(); i++) {\n      for (int j = 0; j < i; j++) {\n        if (dp[j] && words.contains(s.substring(j, i))) { dp[i] = true; break; }\n      }\n    }\n    System.out.println(dp[s.length()] ? "YES" : "NO");\n  }\n}',
      cpp: '#include <iostream>\n#include <sstream>\n#include <unordered_set>\n#include <string>\n#include <vector>\nusing namespace std;\nint main() {\n  string s; getline(cin, s);\n  int n; cin >> n; cin.ignore();\n  string line; getline(cin, line);\n  stringstream ss(line);\n  unordered_set<string> words;\n  string w;\n  while (ss >> w) words.insert(w);\n  vector<bool> dp(s.size() + 1);\n  dp[0] = true;\n  for (int i = 1; i <= (int)s.size(); i++) {\n    for (int j = 0; j < i; j++) {\n      if (dp[j] && words.count(s.substr(j, i - j))) { dp[i] = true; break; }\n    }\n  }\n  cout << (dp[s.size()] ? "YES" : "NO") << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: 'leetcode\n2\nleet code', expectedOutput: 'YES', isSample: true, isHidden: false },
      { input: 'catsandog\n3\ncats dog sand', output: 'NO', expectedOutput: 'NO', isSample: false, isHidden: true },
      { input: 'a\n1\na', expectedOutput: 'YES', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Maximum Subarray Sum',
    description: 'Read n and array. Print maximum sum of contiguous subarray (Kadane).',
    constraints: '1 <= n <= 10^5',
    examples: [{ input: '9\n-2 1 -3 4 -1 2 1 -5 4', output: '6', explanation: 'Subarray [4,-1,2,1]' }],
    difficulty: 'Hard',
    tags: ['dp', 'array'],
    starterCode: {
      python: 'n = int(input())\narr = list(map(int, input().split()))\ncur = best = arr[0]\nfor x in arr[1:]:\n  cur = max(x, cur + x)\n  best = max(best, cur)\nprint(best)',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst arr = lines[1].split(" ").map(Number);\nlet cur = arr[0], best = arr[0];\nfor (let i = 1; i < arr.length; i++) { cur = Math.max(arr[i], cur + arr[i]); best = Math.max(best, cur); }\nconsole.log(best);',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    int cur = sc.nextInt(), best = cur;\n    for (int i = 1; i < n; i++) { cur = Math.max(sc.nextInt(), cur + sc.nextInt()); best = Math.max(best, cur); }\n    System.out.println(best);\n  }\n}',
      cpp: '#include <iostream>\nusing namespace std;\nint main() {\n  int n; cin >> n;\n  int x; cin >> x;\n  long long cur = x, best = x;\n  for (int i = 1; i < n; i++) { cin >> x; cur = max((long long)x, cur + x); best = max(best, cur); }\n  cout << best << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '9\n-2 1 -3 4 -1 2 1 -5 4', expectedOutput: '6', isSample: true, isHidden: false },
      { input: '1\n5', expectedOutput: '5', isSample: false, isHidden: true },
      { input: '3\n-1 -2 -3', expectedOutput: '-1', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Product Except Self',
    description: 'Read n and array. Print product of all elements except self (space-separated).',
    constraints: '2 <= n <= 10^5, no division allowed in logic',
    examples: [{ input: '4\n1 2 3 4', output: '24 12 8 6', explanation: 'Exclude each index' }],
    difficulty: 'Hard',
    tags: ['array', 'prefix-sum'],
    starterCode: {
      python: 'n = int(input())\narr = list(map(int, input().split()))\nres = [1] * n\nprefix = 1\nfor i in range(n):\n  res[i] = prefix\n  prefix *= arr[i]\nsuffix = 1\nfor i in range(n-1, -1, -1):\n  res[i] *= suffix\n  suffix *= arr[i]\nprint(*res)',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst arr = lines[1].split(" ").map(Number);\nconst res = Array(arr.length).fill(1);\nlet prefix = 1;\nfor (let i = 0; i < arr.length; i++) { res[i] = prefix; prefix *= arr[i]; }\nlet suffix = 1;\nfor (let i = arr.length - 1; i >= 0; i--) { res[i] *= suffix; suffix *= arr[i]; }\nconsole.log(res.join(" "));',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    int[] arr = new int[n], res = new int[n];\n    for (int i = 0; i < n; i++) arr[i] = sc.nextInt();\n    int prefix = 1;\n    for (int i = 0; i < n; i++) { res[i] = prefix; prefix *= arr[i]; }\n    int suffix = 1;\n    for (int i = n - 1; i >= 0; i--) { res[i] *= suffix; suffix *= arr[i]; }\n    for (int i = 0; i < n; i++) System.out.print(res[i] + (i + 1 < n ? " " : ""));\n    System.out.println();\n  }\n}',
      cpp: '#include <iostream>\n#include <vector>\nusing namespace std;\nint main() {\n  int n; cin >> n;\n  vector<long long> arr(n), res(n, 1);\n  for (int i = 0; i < n; i++) cin >> arr[i];\n  long long prefix = 1;\n  for (int i = 0; i < n; i++) { res[i] = prefix; prefix *= arr[i]; }\n  long long suffix = 1;\n  for (int i = n - 1; i >= 0; i--) { res[i] *= suffix; suffix *= arr[i]; }\n  for (int i = 0; i < n; i++) { if (i) cout << " "; cout << res[i]; }\n  cout << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '4\n1 2 3 4', expectedOutput: '24 12 8 6', isSample: true, isHidden: false },
      { input: '2\n0 0', expectedOutput: '0 0', isSample: false, isHidden: true },
      { input: '3\n2 3 4', expectedOutput: '12 8 6', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Merge Intervals Count',
    description: 'Read n then n intervals (start end). Print number of merged intervals after merging overlaps.',
    constraints: '1 <= n <= 10^4',
    examples: [{ input: '4\n1 3\n2 6\n8 10\n15 18', output: '3', explanation: '[1,6],[8,10],[15,18]' }],
    difficulty: 'Hard',
    tags: ['intervals', 'sorting'],
    starterCode: {
      python: 'n = int(input())\nintervals = [list(map(int, input().split())) for _ in range(n)]\nintervals.sort()\nmerged = []\nfor s, e in intervals:\n  if not merged or s > merged[-1][1]: merged.append([s, e])\n  else: merged[-1][1] = max(merged[-1][1], e)\nprint(len(merged))',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst n = +lines[0];\nconst intervals = lines.slice(1, 1 + n).map(l => l.split(" ").map(Number)).sort((a,b)=>a[0]-b[0]);\nconst merged = [];\nfor (const [s, e] of intervals) {\n  if (!merged.length || s > merged[merged.length-1][1]) merged.push([s, e]);\n  else merged[merged.length-1][1] = Math.max(merged[merged.length-1][1], e);\n}\nconsole.log(merged.length);',
      java: 'import java.util.*;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    int n = sc.nextInt();\n    int[][] intervals = new int[n][2];\n    for (int i = 0; i < n; i++) { intervals[i][0] = sc.nextInt(); intervals[i][1] = sc.nextInt(); }\n    Arrays.sort(intervals, Comparator.comparingInt(a -> a[0]));\n    List<int[]> merged = new ArrayList<>();\n    for (int[] in : intervals) {\n      if (merged.isEmpty() || in[0] > merged.get(merged.size()-1)[1]) merged.add(in);\n      else merged.get(merged.size()-1)[1] = Math.max(merged.get(merged.size()-1)[1], in[1]);\n    }\n    System.out.println(merged.size());\n  }\n}',
      cpp: '#include <iostream>\n#include <vector>\n#include <algorithm>\nusing namespace std;\nint main() {\n  int n; cin >> n;\n  vector<pair<int,int>> intervals(n);\n  for (int i = 0; i < n; i++) cin >> intervals[i].first >> intervals[i].second;\n  sort(intervals.begin(), intervals.end());\n  vector<pair<int,int>> merged;\n  for (auto [s, e] : intervals) {\n    if (merged.empty() || s > merged.back().second) merged.push_back({s, e});\n    else merged.back().second = max(merged.back().second, e);\n  }\n  cout << merged.size() << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: '4\n1 3\n2 6\n8 10\n15 18', expectedOutput: '3', isSample: true, isHidden: false },
      { input: '2\n1 4\n4 5', expectedOutput: '1', isSample: false, isHidden: true },
      { input: '1\n1 1', expectedOutput: '1', isSample: false, isHidden: true },
    ],
  },
  {
    title: 'Edit Distance',
    description: 'Read two strings word1 and word2. Print minimum edit distance.',
    constraints: '0 <= length <= 500',
    examples: [{ input: 'horse\nros', output: '3', explanation: 'horse -> ros' }],
    difficulty: 'Hard',
    tags: ['dp', 'string'],
    starterCode: {
      python: 'a = input().strip()\nb = input().strip()\nm, n = len(a), len(b)\ndp = [[0]*(n+1) for _ in range(m+1)]\nfor i in range(m+1): dp[i][0] = i\nfor j in range(n+1): dp[0][j] = j\nfor i in range(1, m+1):\n  for j in range(1, n+1):\n    cost = 0 if a[i-1] == b[j-1] else 1\n    dp[i][j] = min(dp[i-1][j] + 1, dp[i][j-1] + 1, dp[i-1][j-1] + cost)\nprint(dp[m][n])',
      javascript: 'const lines = require("fs").readFileSync(0, "utf8").trim().split("\\n");\nconst a = lines[0], b = lines[1];\nconst m = a.length, n = b.length;\nconst dp = Array.from({length: m+1}, () => Array(n+1).fill(0));\nfor (let i = 0; i <= m; i++) dp[i][0] = i;\nfor (let j = 0; j <= n; j++) dp[0][j] = j;\nfor (let i = 1; i <= m; i++) for (let j = 1; j <= n; j++) {\n  const cost = a[i-1] === b[j-1] ? 0 : 1;\n  dp[i][j] = Math.min(dp[i-1][j] + 1, dp[i][j-1] + 1, dp[i-1][j-1] + cost);\n}\nconsole.log(dp[m][n]);',
      java: 'import java.util.Scanner;\npublic class Main {\n  public static void main(String[] args) {\n    Scanner sc = new Scanner(System.in);\n    String a = sc.nextLine(), b = sc.nextLine();\n    int m = a.length(), n = b.length();\n    int[][] dp = new int[m+1][n+1];\n    for (int i = 0; i <= m; i++) dp[i][0] = i;\n    for (int j = 0; j <= n; j++) dp[0][j] = j;\n    for (int i = 1; i <= m; i++) for (int j = 1; j <= n; j++) {\n      int cost = a.charAt(i-1) == b.charAt(j-1) ? 0 : 1;\n      dp[i][j] = Math.min(Math.min(dp[i-1][j] + 1, dp[i][j-1] + 1), dp[i-1][j-1] + cost);\n    }\n    System.out.println(dp[m][n]);\n  }\n}',
      cpp: '#include <iostream>\n#include <string>\n#include <vector>\nusing namespace std;\nint main() {\n  string a, b; getline(cin, a); getline(cin, b);\n  int m = a.size(), n = b.size();\n  vector<vector<int>> dp(m+1, vector<int>(n+1));\n  for (int i = 0; i <= m; i++) dp[i][0] = i;\n  for (int j = 0; j <= n; j++) dp[0][j] = j;\n  for (int i = 1; i <= m; i++) for (int j = 1; j <= n; j++) {\n    int cost = a[i-1] == b[j-1] ? 0 : 1;\n    dp[i][j] = min({dp[i-1][j] + 1, dp[i][j-1] + 1, dp[i-1][j-1] + cost});\n  }\n  cout << dp[m][n] << endl;\n  return 0;\n}',
    },
    testCases: [
      { input: 'horse\nros', expectedOutput: '3', isSample: true, isHidden: false },
      { input: 'intention\nexecution', expectedOutput: '5', isSample: false, isHidden: true },
      { input: 'a\na', expectedOutput: '0', isSample: false, isHidden: true },
    ],
  },
];

async function seed() {
  const uri = process.env.MONGODB_URI || 'mongodb://localhost:27017/oa_practice';
  await mongoose.connect(uri, { serverSelectionTimeoutMS: 5000 });
  await Question.deleteMany({});
  await Question.insertMany(questions);
  console.log(`Seeded ${questions.length} questions`);
  await mongoose.disconnect();
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});
